/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conversor;

import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Formulario extends javax.swing.JFrame { 
   /**
     * Creates new form vistaApp
     */
    double cantidad = 0;
    double conversion = 0;
    String de = "Dolar";
    String a = "Peso";
    ConsumoAPI llamada = new ConsumoAPI();   
   
    public Formulario() {
        initComponents();
        this.setTitle("conversor de divisas");
        this.setLocationRelativeTo(null);
        
    }
    public String aMoneda(double candidad, String moneda){
        return "$"+Math.round(cantidad*100.0)/100.0+" "+moneda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        monedaBase = new javax.swing.JComboBox<>();
        monedaAConvertir = new javax.swing.JComboBox<>();
        CantidadMoneda = new javax.swing.JTextField();
        prueba = new javax.swing.JLabel();
        bConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad");

        jLabel2.setText("De");

        jLabel3.setText("A");

        monedaBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARS", "EUR", "USD", "JPY", "GBP" }));
        monedaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaBaseActionPerformed(evt);
            }
        });

        monedaAConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARS", "EUR", "USD", "JPY", "GBP" }));
        monedaAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaAConvertirActionPerformed(evt);
            }
        });

        CantidadMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadMonedaActionPerformed(evt);
            }
        });
        CantidadMoneda.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CantidadMonedaPropertyChange(evt);
            }
        });

        prueba.setText("resultado");

        bConvertir.setText("convertir");
        bConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monedaAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(416, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monedaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(bConvertir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(prueba)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CantidadMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(monedaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monedaAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bConvertir)
                .addGap(18, 18, 18)
                .addComponent(prueba)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadMonedaActionPerformed

    private void monedaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaBaseActionPerformed
        de = monedaBase.getSelectedItem().toString();
         //convertir();
    }//GEN-LAST:event_monedaBaseActionPerformed

    private void monedaAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaAConvertirActionPerformed
       a = monedaAConvertir.getSelectedItem().toString();
       //convertir();
    }//GEN-LAST:event_monedaAConvertirActionPerformed

    private void CantidadMonedaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CantidadMonedaPropertyChange
      
       
    }//GEN-LAST:event_CantidadMonedaPropertyChange

    private void bConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConvertirActionPerformed
       String srtcantidad = this.CantidadMoneda.getText();
       if(!validarNum(srtcantidad)){
           JOptionPane.showMessageDialog(rootPane,"ingresa una cantidad valida");
       }
       cantidad = Double.parseDouble(srtcantidad);
       
       StringBuilder resultadoF = llamada.llamarAPi(de,a, cantidad);
       
       int startIndex = resultadoF.toString().indexOf("\"rate_for_amount\":\"") + "\"rate_for_amount\":\"".length();
       int endIndex = resultadoF.toString().indexOf("\"", startIndex);

       String rateForAmount = resultadoF.toString().substring(startIndex, endIndex);
       
       String txtFinal = "La cantidad de "+ cantidad + " " + de + " equivalen a " + rateForAmount +" " +a; 
       
        prueba.setText(txtFinal);
       
    }//GEN-LAST:event_bConvertirActionPerformed

    public static boolean validarNum(String datos){
        return datos.matches("^(0|[1-9]\\d*)(\\.\\d+)?$");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Formulario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadMoneda;
    private javax.swing.JButton bConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JComboBox<String> monedaAConvertir;
    private javax.swing.JComboBox<String> monedaBase;
    private javax.swing.JLabel prueba;
    // End of variables declaration//GEN-END:variables
}
